version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: royal_postgres
    environment:
      POSTGRES_DB: royal_pizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend-app:
    build: ../backend-pizza
    container_name: royal_backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/royal_pizza
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - postgres-db

volumes:
  postgres_data:
