services:
  db:
    image: postgres:15
    container_name: royal-pizza-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data   # volume Docker nomm√© pour persistance
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # script d'initialisation
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: royal-pizza-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@royalpizza.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  # backend:
  #   build: ../backend-pizza
  #   container_name: royal-pizza-backend
  #   ports:
  #     - "8081:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

volumes:
  postgres-data:   
